export const validSet = [
                            "AC Recharge", 
                            "Compressor Replacement",
                            "Radiator Service",
                            "Heater Core Repair",
                            "Thermostat/Water Pump",
                            "Battery Replacement",
                            "Alternator/Starter Repair",
                            "Wiring & Fuses",
                            "Radio",
                            "Lighting",
                            "Engine Diagnostics/Check Engine lights",
                            "Engine Repair",
                            "Ignition System",
                            "Fuel System",
                            "Engine Performance Check",
                            "Steering Wheel Adjustment",
                            "Shock and Strut Replacement",
                            "Power Streering Repair",
                            "Steering/Suspension Component Replacement",
                            "Brake Pad Replacement",
                            "Rotor and Drum Replacement",
                            "Brake Caliper",
                            "Anti-Lock Braking Diagnostics and Repair",
                            "Parking/Emergency Brake Repair",
                            "Muffler Replacement",
                            "Catalytic Converter Replacement",
                            "Exhaust Pipe Repair",
                            "Exhaust Pipe Replacement",
                            "Tire Rotation",
                            "Tire Repair",
                            "Tire Replacement",
                            "Tire Rim Repair",
                            "Oil/Filter Replacement",
                            "Coolant Replacement",
                            "Transmission Fluid Replacement",
                            "Power Steering Fluid Replacement",
                            "Brake Fluid Replacement",
                            "Differential Fluid Replacement",
                            "Emission Check",
                            "SeatBelt Replacement",
                            "Door Handle Replacement",
                            "Wiper Replacement",
                            "Seat Replacement"
                        ]